bot:
  name: "gfBot"
  version: "1.0"

# ds_api
deepseek:
  base_url : "https://api.siliconflow.cn/v1"
  api_key : ""

# QQ号，upid为机器人的，good是你的，bad是刻薄猫娘
QQ_ID :
  up_id : ""
  good_id : 
  bad_id : 



function :
  mmPic : false   #喵喵p图
  mmgal : true    #喵喵gal 
  mmStudy : true  #喵喵学习
  mmSpeak : true  #喵喵聊天
